# Form implementation generated from reading ui file 'GraphsWin.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Graph(object):
    def setupUi(self, Graph):
        Graph.setObjectName("Graph")
        Graph.resize(707, 547)
        self.original_signal = QtWidgets.QLabel(Graph)
        self.original_signal.setGeometry(QtCore.QRect(20, 50, 641, 181))
        self.original_signal.setText("")
     
        self.original_signal.setScaledContents(True)
        self.original_signal.setObjectName("original_signal")
        self.label_9 = QtWidgets.QLabel(Graph)
        self.label_9.setGeometry(QtCore.QRect(270, 5, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Graph)
        self.label_10.setGeometry(QtCore.QRect(260, 250, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.sampled_signal = QtWidgets.QLabel(Graph)
        self.sampled_signal.setGeometry(QtCore.QRect(20, 300, 641, 181))
        self.sampled_signal.setText("")
        self.sampled_signal.setScaledContents(True)
        self.sampled_signal.setObjectName("sampled_signal")
        self.txtNewSample = QtWidgets.QLabel(Graph)
        self.txtNewSample.setGeometry(QtCore.QRect(30, 490, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.txtNewSample.setFont(font)
        self.txtNewSample.setObjectName("txtNewSample")
        self.decimationFact = QtWidgets.QLabel(Graph)
        self.decimationFact.setGeometry(QtCore.QRect(400, 490, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.decimationFact.setFont(font)
        self.decimationFact.setObjectName("decimationFact")

        self.retranslateUi(Graph)
        QtCore.QMetaObject.connectSlotsByName(Graph)

    def retranslateUi(self, Graph):
        _translate = QtCore.QCoreApplication.translate
        Graph.setWindowTitle(_translate("Graph", "Form"))
        self.label_9.setText(_translate("Graph", "Señal original"))
        self.label_10.setText(_translate("Graph", "Señal muestreada"))
        self.txtNewSample.setText(_translate("Graph", "Nueva frecuencia de muestreo:"))
        self.decimationFact.setText(_translate("Graph", "Factor de decimación:"))
